#!/bin/bash
#SBATCH -J Merfish   # Job name
#SBATCH -o Merfish.out          # Standard output file
#SBATCH -e Merfish_error.out 
#SBATCH -p RTX4090              # Partition name
#SBATCH --qos=normal            # Quality of Service
#SBATCH -N 1                    # Request 1 node
#SBATCH -n 1                    # Request 1 task
#SBATCH -c 64                   # Request 16 CPU cores per task
#SBATCH --gres=gpu:0
#SBATCH --mem=128G              # Request 128GB RAM

# ==========================================
# Environment Setup
# ==========================================
# Load bashrc to enable conda
source ~/.bashrc

echo "Job ID: $SLURM_JOB_ID"
echo "Node: $SLURMD_NODENAME"
echo "Start time: $(date)"
echo "------------------------------------------------"

# ==========================================
# 1. Run Seurat.py
# ==========================================
# This script handles:
# 1. Reading RDS and converting to MTX (if not already done)
# 2. Running Seurat RPCA workflow
# 3. Generating visualizations

# Activate environment
conda activate seurat

echo "[Step 1/2] Running Seurat.py..."
python Seurat.py

# Check if the previous step was successful (exit code 0)
if [ $? -ne 0 ]; then
    echo "Error: Seurat.py failed. Exiting pipeline."
    exit 1
fi

echo "------------------------------------------------"

# ==========================================
# 2. Run PCA.py
# ==========================================
# This script handles:
# 1. Reading the MTX file generated by Seurat.py
# 2. Running Scanpy PCA workflow
# 3. Generating visualizations

# Activate environment
conda deactivate
conda activate patchformer

echo "[Step 2/2] Running PCA.py..."
python PCA.py

echo "------------------------------------------------"
echo "All jobs finished at $(date)"
